config/routes.rb
Rails.application.routes.draw do
  

  namespace :admin do 
    root 'base#index'
    
    resources :projects, only: [:new, :create, :destroy]
    resources :users
  end

  resources :projects, only: [:index, :edit, :show, :update] do 
    resources :tickets
  end
  
  devise_for :users

   root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true 
  has_many :tickets, dependent: :delete_all
  has_many :roles, dependent: :delete_all
  
  def has_member?(user)
    roles.exists?(user_id: user)
  end
  
  [:manager, :editor, :viewer].each do |role|
    define_method "has_#{role}?" do |user|
      roles.exists?(user_id: user, role: role)
    end
  end
end
  

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  
  # GET /projects/new
  def new
    @project = Project.new
  end

# POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created."

      redirect_to @project
    else
      flash.now[:alert] = "Project has not been created."

      render "new"
    end
  end
  

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project has been successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private 
  def project_params
      params.require(:project).permit(:name, :description)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = policy_scope(Project)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    authorize @project, :show?
  end

  
  # GET /projects/1/edit
  def edit
    authorize @project, :update?
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize @project, :update?
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project has been updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        flash.now[:alert] = "Project has not been updated."
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The project you were looking" + " for could not be found."
        redirect_to projects_path 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.input :name %>
<%= f.input :description %>
<%= f.button :submit, class: "btn-primary"%>  
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
<h1>Editing project</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="page-header">
<h1>Listing projects</h1>
<%= admins_only do %>
<ul class="actions">
<%= link_to 'New Project', new_admin_project_path, class: "new" %>
</ul>
<% end %>
</div>
 <% @projects.each do |project| %>
      
 <h2><li><%= link_to project.name, project %></li></h2>
       
 <% end %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h2><%= @project.name %></h2>
<ul class="actions">
<% if policy(@project).update? %>
<li><%= link_to 'Edit Project', edit_project_path(@project), class: 'edit' %></li>
<% end %>
<% admins_only do %>
<li><%= link_to 'Delete Project', admin_project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %></li>
<% end %>
</ul>
</div>
<div class="page-header">
	<h2>Tickets</h2>
	
	<ul class="actions">
		<% if policy(Ticket.new(project: @project)).create? %>
		<li><%= link_to "New Ticket", new_project_ticket_path(@project), class: "new" %> </li>
	    <% end %>
	</ul>
	
	<ul id="tickets">
	<% @project.tickets.each do |ticket| %>
	<li>
		#<%= ticket.id %>-
		<%= link_to ticket.title, [@project, ticket]%>
	</li>
	<% end %>
	</ul>
</div>